GET http://localhost:3000/api/inmuebles

###
GET http://localhost:3000/api/inmuebles/636642b3b1d989401208e723

###
POST http://localhost:3000/api/inmuebles
Content-Type: application/json

{
    "piso": 3,
    "letra": "A",
    "extension": 86,
    "num_habitaciones": 3,
    "alquilado": false,
    "nombre_propietario": "María",
    "email_contacto": "maria@gmail.com"
}

###
PUT http://localhost:3000/api/inmuebles/636642deb1d989401208e725
Content-Type: application/json

{
    "alquilado": true
}

###
DELETE http://localhost:3000/api/inmuebles/636642deb1d989401208e725